language: cpp
compiler:
  - gcc
  - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq mpich2 libmpich2-dev libcppunit-1.12-1 libcppunit-dev libtool automake 
 - mkdir -p /usr/local/lib
script: autoreconf -i && CPPFLAGS="-I/usr/include/mpich2" ./configure --prefix=/usr/local/lib/warped --enable-cppunit && make && make install && make check